version: '3.8'

services:
  flask_app:
    build: .
    container_name: flask_app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mongo
      - redis
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0 --port=8080
    platform: linux/amd64   # Use this if you want to force amd64 on Apple Silicon

  mongo:
    image: mongo:7.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  mongo_data:
